const questions = [
  // {
  //   id: 0,
  //   q: "onus",
  //   example: "The onus is on the captain to lead the team to victory.",
  //   definition: "A responsibility or duty that someone is expected to take on.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  {
    id: 1,
    q: "gnawing",
    // pronunciation: "",
    definition:
      "Biting or chewing something repeatedly, often to wear it down or break it apart. Can also mean a constant, annoying pain or feeling, like something biting or chewing at you.",
    example:
      "The gnawing hunger in my stomach made it difficult to concentrate on anything else.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 2,
    q: "rind",
    example: "He grated the lemon rind and added it to the cake mixture.",
    definition:
      "the hard outer layer of cheese, or the tough outer skin of fruits like lemons or oranges.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 3,
    q: "defiantly",
    definition:
      "doing something in a bold, rebellious way to show you’re not willing to obey or agree.",
    example:
      "She refused to tidy her room, crossing her arms and frowning defiantly",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  // {
  //   id: 4,
  //   q: "senile",
  //   example:
  //     "The elderly man was becoming somewhat senile, often forgetting where he left his keys.",
  //   definition:
  //     "Someone who has lost the ability to think clearly or remember things, usually because of old age.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 5,
  //   q: "slander",
  //   definition:
  //     "saying something untrue about someone to harm their reputation.",
  //   example: "Mark's false claim that Emma cheated in her exam was slander.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 6,
  //   q: "vessel",
  //   definition:
  //     "something that carries something else, like a ship that carries people or goods, a blood vessel that carries blood in the body, or a drinking container like a mug or cup.",
  //   example:
  //     "The large vessel carried thousands of passengers across the ocean.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 7,
  //   q: "permit (noun) - note that the stress is on the first syllable",
  //   definition: "An official document that gives permission to do something",
  //   example: "You need a permit to park your car in this area.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 8,
  //   q: "permit (verb) - note that the stress is on the second syllable",
  //   definition: "To allow something to happen.",
  //   example:
  //     "The teacher does not permit students to use their phones in class.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 9,
  //   q: "douse",
  //   definition: "To drench or soak someone or something in liquid.",
  //   example: "She had to douse the fire with water to stop it from spreading.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 10,
  //   q: "sane",
  //   definition: "Mentally healthy; of sound mind",
  //   example:
  //     "After a long holiday in a sunny country, I finally feel sane again.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 11,
  //   q: "corrugated",
  //   definition:
  //     "Having a surface that is wavy or ridged, like the folds of a cardboard box.",
  //   example: "The roof of the shed was made of corrugated metal sheets.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  {
    id: 12,
    q: "apocryphal",
    definition:
      "A story or statement that is widely believed but probably not true.",
    example:
      "The apocryphal tale of a haunted house scared the children at bedtime.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 13,
    q: "rustle",
    definition:
      "Definition 1: A soft, crackling sound, often made by something like leaves or paper. Definition 2 (to rustle something up): To quickly prepare or gather something, often food or supplies.",
    example:
      "Example 1: I could hear the rustle of the wind moving through the trees. Example 2: I can rustle up some sandwiches if you’re hungry.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 14,
    q: "digression",
    definition:
      "When someone talks about something unrelated to the main topic, or deviates from a route on a journey.",
    example:
      "His speech was full of digressions, and it took a while to get back to the main point.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 15,
    q: "burrow",
    definition: "A hole or tunnel dug by an animal to live in",
    example: "The rabbit disappeared into its burrow to hide from the fox.",
    options: ["yes", "no"],
    a: 0,
    category: "known",
  },
  {
    id: 16,
    q: "anaemic",
    definition:
      "Lacking enough iron, which can make a person feel tired and weak.",
    example:
      "The doctor said she was anaemic and needed to eat more iron-rich foods",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 17,
    q: "muzzle",
    definition:
      "A covering for the mouth and nose of an animal, often used to stop it from biting or eating.",
    example:
      "The dog wore a muzzle while visiting the vet to keep everyone safe.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 18,
    q: "assault",
    definition: "A violent attack on someone, either physically or verbally.",
    example:
      "The knight defended the castle from an assault by the enemy soldiers.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 19,
    q: "gradual",
    definition: "Happening slowly over time, not all at once.",
    example: "The hill had a gradual slope, making it easy to climb.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 20,
    q: "prime",
    definition:
      "The best or most important part of something, or a number only divisible by 1 and itself.",
    example:
      "At 25, he felt he was in the prime of his life, full of energy and ideas.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  // {
  //   id: 21,
  //   q: "dementia",
  //   definition:
  //     "a medical condition that affects the brain, which is more common in older age and makes it hard to remember things or think clearly.",
  //   example: "Grandma sometimes forgets things because she has dementia.",
  //   options: ["yes", "no"],
  // category: "known",
  //   a: 0,
  // },
  // {
  //   id: 22,
  //   q: "hatch",
  //   definition:
  //     "To open or create an opening, or when a baby bird or reptile comes out of an egg.",
  //   example: "The chicks began to hatch from their eggs in the early morning.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  {
    id: 23,
    q: "maintenance",
    definition:
      "The act of keeping something in good condition by checking or repairing it regularly.",
    example: "Regular maintenance of his bike kept it running smoothly.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 24,
    q: "logical",
    definition: "Using clear and sensible reasoning.",
    example: "It’s logical to wear a coat when it’s cold outside.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 25,
    q: "assert",
    definition: "To state something confidently and clearly.",
    example:
      "Harry asserted that he was telling the truth about the missing homework.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 26,
    q: "confound",
    definition: "To surprise or confuse someone.",
    example: "The magician’s tricks continued to confound the audience.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 27,
    q: "fractious",
    definition: "Easily annoyed, or difficult to manage.",
    example:
      "The fractious toddler threw a tantrum when he didn’t get his way.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 28,
    q: "Ingrate",
    definition: "A person who is not thankful.",
    example:
      "After all the help she gave him, he acted like an ingrate and didn’t even say thank you.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 29,
    q: "Precise",
    definition: "Very accurate and exact.",
    example:
      "The instructions for building the model were precise, leaving no room for mistakes.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 30,
    q: "Trove",
    definition: "A collection of valuable things.",
    example: "The attic was a trove of old toys and forgotten treasures.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 31,
    q: "hypothetical",
    definition:
      "Something that is hypothetical is an idea or situation that is not real but is suggested to explore possibilities. In science, a hypothesis can be tested through experiments to see if it could be true.",
    example:
      "The professor gave a hypothetical example to explain the complex idea.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 32,
    q: "marred",
    definition: "Damaged or spoiled to a certain extent.",
    example:
      "The beauty of the painting was marred by a scratch across the canvas.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 33,
    q: "episode",
    definition: "An incident or event in a series.",
    example:
      "The first episode of the TV programme had me laughing from start to finish.",
    options: ["yes", "no"],
    a: 0,
    category: "known",
  },
  {
    id: 34,
    q: "mire",
    definition:
      "A stretch of swampy or boggy ground; a difficult or unpleasant situation.",
    example: "His car got stuck in the mire after the heavy rain.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 35,
    q: "deduce",
    definition: "To work something out by thinking logically about the facts.",
    example:
      "By examining the footprints in the snow, the detective was able to deduce that the thief had escaped through the back door.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 36,
    q: "negligible",
    definition: "So small or unimportant that it can usually be ignored.",
    example:
      "The difference in size between the two objects was so negligible that it was hard to notice",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 37,
    q: "implode",
    definition: "When something collapses in on itself",
    example: "The building will implode in a controlled demolition.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 38,
    q: "acute",
    definition: "Something very sharp, intense or short-lived",
    example: "I had an acute pain in my leg when I cut it.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 39,
    q: "accommodate",
    definition: "To provide space or meet someone's needs.",
    example:
      "The stadium can accommodate thousands of football fans for the big match.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 40,
    q: "copse",
    definition: "A small group of trees.",
    example:
      "Alex hid behind a copse in Minecraft to avoid being chased by zombies.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 41,
    q: "abandon",
    definition: "To leave something behind or to stop doing something.",
    example: "I had to abandon my plan to move to Spain after Brexit.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 42,
    q: "multitudinous ",
    definition: "very many; too many to count",
    example:
      "The Roblox game had multitudinous levels, each more exciting than the last.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 43,
    q: "dogged",
    definition:
      "Definition 1 (adjective) never giving up; determined. E.g. 'with dogged effort, he finally scored the winning goal in football.'. Definition 2 (verb): followed, pursued or hounded. E.g. 'the project was dogged by problems from the outset.'",
    // example: "",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 44,
    q: "abase",
    definition: "to make someone feel small or unimportant; to shame someone.",
    example:
      "The arrogant player tried to abase his teammate, but the coach defended him.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 45,
    q: "confront",
    definition:
      "To face a problem or challenge, often by speaking to someone about the problem in a direct manner",
    example: "She had to confront the Ender Dragon to win her Minecraft world.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 46,
    q: "nimble",
    definition: "Quick and light in movement.",
    example:
      "His nimble feet helped him dribble past the defenders in football.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 47,
    q: "savvy",
    definition: "Having good knowledge, understanding or awareness",
    example: "His Roblox savvy made him popular with thousands of players.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 48,
    q: "assiduous ",
    definition: "hard-working and careful.",
    example:
      "The assiduous player practised free kicks daily to improve his skills.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 49,
    q: "doleful ",
    definition: "Very sad or sorrowful.",
    example: "His doleful face showed how much he hated losing the match.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 50,
    q: "truant",
    definition: "Someone who skips school or duties without permission.",
    example:
      "He played Roblox all day instead of attending school, becoming a truant.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 51,
    q: "inhibit",
    definition: "to stop or slow something down.",
    example: "The lag in Minecraft would inhibit his ability to fight mobs.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 52,
    q: "frequent (used as a verb)",
    definition: "To visit a place often.",
    example: "He would frequent the football pitch to practise his skills.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 53,
    q: "prescience",
    definition: "Knowing something before it happens.",
    example:
      "He guessed the result of the football game with incredible prescience",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 54,
    q: "artless",
    definition: "Lacking skill or knowledge.",
    example:
      "His artless build in Minecraft was full of mistakes, but it was still fun.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 55,
    q: "noteworthy",
    definition: "Important or deserving attention.",
    example:
      "Scoring the winning goal was a noteworthy moment in the football match.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 56,
    q: "schism",
    definition: "A division or split into two parts.",
    example:
      "A schism formed in the Minecraft server when players disagreed on which game mode to play.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 57,
    q: "furrow",
    definition: "A long, narrow groove or line.",
    example:
      "The farmer made a furrow in the soil before planting crops for the holiday feast.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 58,
    q: "uncouth",
    definition: "Rude or lacking manners.",
    example: "His uncouth behaviour on holiday annoyed everyone in his family.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 59,
    q: "dwelling",
    definition: "A place where someone lives.",
    example: "In Minecraft, I built a cosy dwelling out of wood and stone.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 60,
    q: "procure",
    definition: "To get or obtain something.",
    example:
      "I had to procure a football from the store for our holiday tournament.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 61,
    q: "conscientious",
    definition: "Very careful and responsible.",
    example:
      "He was conscientious, always working hard on his homework and ensuring he had completed it thoroughly and accurately.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 62,
    q: "insinuate",
    definition: "To hint or suggest something indirectly.",
    example:
      "He tried to insinuate that I had cheated during the Minecraft challenge.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 63,
    q: "abduct",
    definition: "To take someone away by force.",
    example:
      "In Roblox, players might pretend to abduct their friends as part of a game plot.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 65,
    q: "Avow",
    definition: "To declare openly.",
    example: "She avowed her love for football, never missing a single match.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 66,
    q: "Embolden",
    definition: "To give someone courage or confidence.",
    example:
      "Scoring the first goal emboldened the team to push forward aggressively.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 67,
    q: "Intimidate",
    definition: "To frighten or overawe someone.",
    example:
      "The towering defenders tried to intimidate the striker, but he remained unfazed.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 68,
    q: "Oblique",
    definition: "Not straightforward or at an angle.",
    example: "He took an oblique shot at goal, surprising the goalkeeper.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 69,
    q: "Oppression",
    definition: "Cruel or unfair treatment.",
    example:
      "The villagers in Roblox rebelled against the king’s oppression by building a fortress.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 70,
    q: "Prosaic",
    definition: "Lacking imagination; dull.",
    example: "His prosaic game strategy failed, and his team lost the match.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 71,
    q: "Scuttle",
    definition: "To move quickly with short steps.",
    example: "The creeper scuttled towards him in Minecraft.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  // template
  // {
  //   id: 2,
  //   q: "",
  //   definition: "",
  //   example: "",
  //   options: ["yes", "no"],
  // category: "unknown",
  //   a: 0,
  // },
];
