const questions = [
  // {
  //   id: 0,
  //   q: "onus. Example usage: The onus is on the captain to lead the team to victory.",
  //   definition: "A responsibility or duty that someone is expected to take on.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  {
    id: 1,
    q: "gnawing. Example usage: The gnawing hunger in my stomach made it difficult to concentrate on anything else.",
    definition:
      "Biting or chewing something repeatedly, often to wear it down or break it apart. Can also mean a constant, annoying pain or feeling, like something biting or chewing at you.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 2,
    q: "rind. Example usage: he grated the lemon rind and added it to the cake mixture.",
    definition:
      "the hard outer layer of cheese, or the tough outer skin of fruits like lemons or oranges.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 3,
    q: "defiantly. Example usage: she refused to tidy her room, crossing her arms and frowning defiantly",
    definition:
      "doing something in a bold, rebellious way to show you’re not willing to obey or agree.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  // {
  //   id: 4,
  //   q: "senile",
  //   example:
  //     "The elderly man was becoming somewhat senile, often forgetting where he left his keys.",
  //   definition:
  //     "Someone who has lost the ability to think clearly or remember things, usually because of old age.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 5,
  //   q: "slander. Example usage: Mark's false claim that Emma cheated in her exam was slander.",
  //   definition:
  //     "saying something untrue about someone to harm their reputation.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 6,
  //   q: "vessel",
  //   definition:
  //     "something that carries something else, like a ship that carries people or goods, a blood vessel that carries blood in the body, or a drinking container like a mug or cup.",
  //   example:
  //     "The large vessel carried thousands of passengers across the ocean.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 7,
  //   q: "permit (noun). Example usage: you need a permit to park your car in this area.",
  //   definition: "An official document that gives permission to do something",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 8,
  //   q: "permit (verb) - note that the stress is on the second syllable",
  //   definition: "To allow something to happen.",
  //   example:
  //     "The teacher does not permit students to use their phones in class.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 9,
  //   q: "douse. Example usage: She had to douse the fire with water to stop it from spreading.",
  //   definition: "To drench or soak someone or something in liquid.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 10,
  //   q: "sane. Example usage: After a long holiday in a sunny country, I finally feel sane again.",
  //   definition: "Mentally healthy; of sound mind",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  // {
  //   id: 11,
  //   q: "corrugated. Example usage: The roof of the shed was made of corrugated metal sheets.",
  //   definition:
  //     "Having a surface that is wavy or ridged, like the folds of a cardboard box.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  {
    id: 12,
    q: "apocryphal. Example usage: The apocryphal tale of a haunted house scared the children at bedtime.",
    definition:
      "A story or statement that is widely believed but probably not true.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 13,
    q: "rustle",
    definition:
      "Definition 1: A soft, crackling sound, often made by something like leaves or paper. Definition 2 (to rustle something up): To quickly prepare or gather something, often food or supplies.",
    example:
      "Example 1: I could hear the rustle of the wind moving through the trees. Example 2: I can rustle up some sandwiches if you’re hungry.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 14,
    q: "digression",
    definition:
      "When someone talks about something unrelated to the main topic, or deviates from a route on a journey.",
    example:
      "His speech was full of digressions, and it took a while to get back to the main point.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 15,
    q: "burrow. Example usage: The rabbit disappeared into its burrow to hide from the fox.",
    definition: "A hole or tunnel dug by an animal to live in",
    options: ["yes", "no"],
    a: 0,
    category: "known",
  },
  {
    id: 16,
    q: "anaemic. Example usage: the doctor said she was anaemic and needed to eat more iron-rich foods.",
    definition:
      "Lacking enough iron, which can make a person feel tired and weak.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 17,
    q: "muzzle",
    definition:
      "A covering for the mouth and nose of an animal, often used to stop it from biting or eating.",
    example:
      "The dog wore a muzzle while visiting the vet to keep everyone safe.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 18,
    q: "assault",
    definition: "A violent attack on someone, either physically or verbally.",
    example:
      "The knight defended the castle from an assault by the enemy soldiers.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 19,
    q: "gradual. Example usage: The hill had a gradual slope, making it easy to climb.",
    definition: "Happening slowly over time, not all at once.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 20,
    q: "prime",
    definition:
      "The best or most important part of something, or a number only divisible by 1 and itself.",
    example:
      "At 25, he felt he was in the prime of his life, full of energy and ideas.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  // {
  //   id: 21,
  //   q: "dementia. Example usage: Grandma sometimes forgets things because she has dementia.",
  //   definition:
  //     "a medical condition that affects the brain, which is more common in older age and makes it hard to remember things or think clearly.",
  //   options: ["yes", "no"],
  // category: "known",
  //   a: 0,
  // },
  // {
  //   id: 22,
  //   q: "hatch. Example usage: the chicks began to hatch from their eggs in the early morning.",
  //   definition:
  //     "To open or create an opening, or when a baby bird or reptile comes out of an egg.",
  //   options: ["yes", "no"],
  //   a: 0,
  // },
  {
    id: 23,
    q: "maintenance. Example usage: Regular maintenance of his bike kept it running smoothly.",
    definition:
      "The act of keeping something in good condition by checking or repairing it regularly.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 24,
    q: "logical. Example usage: It's logical to wear a coat when it's cold outside.",
    definition: "Using clear and sensible reasoning.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 25,
    q: "assert",
    definition: "To state something confidently and clearly.",
    example:
      "Harry asserted that he was telling the truth about the missing homework.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 26,
    q: "confound. Example usage: the magician's tricks continued to confound the audience.",
    definition: "To surprise or confuse someone.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 27,
    q: "fractious",
    definition: "Easily annoyed, or difficult to manage.",
    example:
      "The fractious toddler threw a tantrum when he didn’t get his way.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 28,
    q: "Ingrate",
    definition: "A person who is not thankful.",
    example:
      "After all the help she gave him, he acted like an ingrate and didn’t even say thank you.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 29,
    q: "Precise",
    definition: "Very accurate and exact.",
    example:
      "The instructions for building the model were precise, leaving no room for mistakes.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 30,
    q: "Trove. Example usage: the attic was a trove of old toys and forgotten treasures.",
    definition: "A collection of valuable things.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 31,
    q: "hypothetical",
    definition:
      "Something that is hypothetical is an idea or situation that is not real but is suggested to explore possibilities. In science, a hypothesis can be tested through experiments to see if it could be true.",
    example:
      "The professor gave a hypothetical example to explain the complex idea.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 32,
    q: "marred",
    definition: "Damaged or spoiled to a certain extent.",
    example:
      "The beauty of the painting was marred by a scratch across the canvas.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 33,
    q: "episode",
    definition: "An incident or event in a series.",
    example:
      "The first episode of the TV programme had me laughing from start to finish.",
    options: ["yes", "no"],
    a: 0,
    category: "known",
  },
  {
    id: 34,
    q: "mire. Example usage: his car got stuck in the mire after the heavy rain.",
    definition:
      "A stretch of swampy or boggy ground; a difficult or unpleasant situation.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 35,
    q: "deduce",
    definition: "To work something out by thinking logically about the facts.",
    example:
      "By examining the footprints in the snow, the detective was able to deduce that the thief had escaped through the back door.",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 36,
    q: "negligible",
    definition: "So small or unimportant that it can usually be ignored.",
    example:
      "The difference in size between the two objects was so negligible that it was hard to notice",
    options: ["yes", "no"],
    a: 0,
    category: "unknown",
  },
  {
    id: 37,
    q: "implode. Example usage: the building will implode in a controlled demolition.",
    definition: "When something collapses in on itself",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 38,
    q: "acute. Example usage: I had an acute pain in my leg when I cut it.",
    definition: "Something very sharp, intense or short-lived",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 39,
    q: "accommodate",
    definition: "To provide space or meet someone's needs.",
    example:
      "The stadium can accommodate thousands of football fans for the big match.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 40,
    q: "copse",
    definition: "A small group of trees.",
    example:
      "Alex hid behind a copse in Minecraft to avoid being chased by zombies.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 41,
    q: "abandon. Example usage: I had to abandon my plan to move to Spain after Brexit.",
    definition: "To leave something behind or to stop doing something.",
    options: ["yes", "no"],
    category: "known",
    a: 0,
  },
  {
    id: 42,
    q: "multitudinous ",
    definition: "very many; too many to count",
    example:
      "The Roblox game had multitudinous levels, each more exciting than the last.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 43,
    q: "dogged. Example usage: she had dogged determination to finish the project",
    definition:
      "Definition 1 (adjective) never giving up; determined. E.g. 'with dogged effort, he finally scored the winning goal in football.'. Definition 2 (verb): followed, pursued or hounded. E.g. 'the project was dogged by problems from the outset.'",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 44,
    q: "abase",
    definition: "to make someone feel small or unimportant; to shame someone.",
    example:
      "The arrogant player tried to abase his teammate, but the coach defended him.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 45,
    q: "confront. Example usage: She had to confront the Ender Dragon to win her Minecraft world.",
    definition:
      "To face a problem or challenge, often by speaking to someone about the problem in a direct manner",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 46,
    q: "nimble",
    definition: "Quick and light in movement.",
    example:
      "His nimble feet helped him dribble past the defenders in football.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 47,
    q: "savvy. Example usage: His Roblox savvy made him popular with thousands of players.",
    definition: "Having good knowledge, understanding or awareness",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 48,
    q: "assiduous ",
    definition: "hard-working and careful.",
    example:
      "The assiduous player practised free kicks daily to improve his skills.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 49,
    q: "doleful. Example usage: His doleful face showed how much he hated losing the match.",
    definition: "Very sad or sorrowful.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 50,
    q: "truant",
    definition: "Someone who skips school or duties without permission.",
    example:
      "He played Roblox all day instead of attending school, becoming a truant.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 51,
    q: "inhibit. Example usage: the lag in Minecraft inhibited his ability to fight mobs.",
    definition: "to stop or slow something down.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 52,
    q: "frequent (used as a verb). Example usage: He would frequent the football pitch to practise his skills.",
    definition: "To visit a place often.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 53,
    q: "prescience. Example usage: He guessed the result of the football game with incredible prescience",
    definition: "Knowing something before it happens.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 54,
    q: "artless. Example usage: His artless build in Minecraft was full of mistakes, but it was still fun.",
    definition: "Lacking skill or knowledge.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 55,
    q: "noteworthy. Example usage: Scoring the winning goal was a noteworthy moment in the football match.",
    definition: "Important or deserving attention.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 56,
    q: "schism",
    definition:
      "A division or split into two parts. Example usage: a schism formed in the Minecraft server when players disagreed on which game mode to play.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 57,
    q: "furrow",
    definition: "A long, narrow groove or line.",
    example:
      "The farmer made a furrow in the soil before planting crops for the holiday feast.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 58,
    q: "uncouth. Example usage: his uncouth behaviour on holiday annoyed everyone in his family",
    definition: "Rude or lacking manners.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 59,
    q: "dwelling. Example usage: In Minecraft, I built a cosy dwelling out of wood and stone.",
    definition: "A place where someone lives.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 60,
    q: "procure",
    definition: "To get or obtain something.",
    example:
      "I had to procure a football from the store for our holiday tournament.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 61,
    q: "conscientious. Example usage: He was conscientious, always working hard on his homework and ensuring he had completed it thoroughly and accurately.",
    definition: "Very careful and responsible.",

    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 62,
    q: "insinuate. Example usage: He tried to insinuate that I had cheated during the Minecraft challenge.",
    definition: "To hint or suggest something indirectly.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 63,
    q: "abduct",
    definition: "To take someone away by force.",
    example:
      "In Roblox, players might pretend to abduct their friends as part of a game plot.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 65,
    q: "Avow. Example usage: She avowed her love for football, never missing a single match.",
    definition: "To declare openly.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 66,
    q: "Embolden",
    definition: "To give someone courage or confidence.",
    example:
      "Scoring the first goal emboldened the team to push forward aggressively.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 67,
    q: "Intimidate",
    definition: "To frighten or overawe someone.",
    example:
      "The towering defenders tried to intimidate the striker, but he remained unfazed.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 68,
    q: "Oblique. Example usage: He took an oblique shot at goal, surprising the goalkeeper.",
    definition: "Not straightforward or at an angle.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 69,
    q: "Oppression",
    definition: "Cruel or unfair treatment.",
    example:
      "The villagers in Roblox rebelled against the king’s oppression by building a fortress.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 70,
    q: "Prosaic. Example usage: his prosaic game strategy failed, and his team lost the match.",
    definition: "Lacking imagination; dull.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 71,
    q: "Scuttle. Example usage: the creeper scuttled towards him in Minecraft.",
    definition: "To move quickly with short steps.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },

  {
    id: 72,
    q: "twilight. Example usage: The sky turned purple during twilight as the sun slipped below the horizon.",
    definition:
      "The soft light in the sky just after sunset or just before sunrise.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 73,
    q: "conjecture. Example usage: Her explanation was just a conjecture, not based on any real evidence.",
    definition: "An idea or guess based on limited information.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 74,
    q: "nonconformist. Example usage: He was known as a nonconformist who never followed the crowd.",
    definition:
      "Someone who doesn’t follow the usual rules or ways of doing things.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 75,
    q: "dusk. Example usage: At dusk, the streetlights began to glow as daylight faded.",
    definition: "The time in the evening just before it gets dark.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 76,
    q: "pretence. Example usage: He made a pretence of being asleep so he wouldn’t have to talk.",
    definition: "The act of pretending something is true when it isn’t.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 77,
    q: "initiate. Example usage: The teacher decided to initiate a new reading programme this term.",
    definition: "To begin something or make it start.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 78,
    q: "abate. Example usage: The storm finally began to abate after several hours.",
    definition: "To become weaker or less strong.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 79,
    q: "assortment. Example usage: The gift basket contained an assortment of sweets and chocolates.",
    definition: "A mixture or variety of different things.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 80,
    q: "scapegoat. Example usage: He became the scapegoat for mistakes made by the whole team.",
    definition:
      "A person who is unfairly blamed for something bad that others did.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 81,
    q: "frugal. Example usage: She’s very frugal and always finds ways to save money.",
    definition: "Careful about not wasting money or resources.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 82,
    q: "abdicate. Example usage: The king chose to abdicate the throne and live a quiet life.",
    definition:
      "To give up a powerful position, like a king or queen stepping down.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 83,
    q: "innocuous. Example usage: The question seemed innocuous, but it caused quite a stir.",
    definition: "Not harmful or dangerous.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 84,
    q: "fruitful. Example usage: Their meeting was fruitful and led to several new ideas.",
    definition: "Producing good results or lots of something useful.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 85,
    q: "nondescript. Example usage: He wore a nondescript outfit that no one noticed.",
    definition: "Not interesting or special; hard to describe.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 86,
    q: "duplicitous. Example usage: The spy led a duplicitous life, pretending to work for both sides.",
    definition:
      "Dishonest or tricky, pretending to be one thing while doing another.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 87,
    q: "conjure. Example usage: The magician seemed to conjure a rabbit out of thin air.",
    definition:
      "To make something appear as if by magic, or to bring an image to mind.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 88,
    q: "procession. Example usage: The wedding procession moved slowly through the village.",
    definition:
      "A line of people or vehicles moving slowly in an organised way, often for a ceremony.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 89,
    q: "scarce. Example usage: Water became scarce during the long drought.",
    definition: "Hard to find or not enough of something.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 90,
    q: "tyrant. Example usage: The people lived in fear under the rule of a cruel tyrant.",
    definition: "A cruel or unfair ruler who has total power.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 91,
    q: "abyss. Example usage: He stared into the dark abyss, feeling dizzy from the height.",
    definition: "A deep, dark hole or space that seems endless.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 92,
    q: "unsubstantiated. Example usage: Her claim was unsubstantiated and lacked evidence.",
    definition: "Not proven to be true; lacking evidence.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 93,
    q: "scrutiny. Example usage: The documents were under close scrutiny during the investigation.",
    definition: "Careful and detailed examination of something.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 94,
    q: "clench. Example usage: He had to clench his teeth to stop himself from shouting.",
    definition: "To squeeze something tightly, often because of anger or fear.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 95,
    q: "profuse. Example usage: She offered profuse thanks for the kind gift.",
    definition: "A large amount of something, more than needed.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 96,
    q: "obfuscate. Example usage: The politician tried to obfuscate the facts during the interview.",
    definition: "To make something confusing or unclear on purpose.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 97,
    q: "aviation. Example usage: He studied aviation because he wanted to become a pilot.",
    definition: "The flying or operating of aircraft.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 98,
    q: "gloaming. Example usage: The village looked peaceful in the gloaming.",
    definition: "Another word for twilight or the time just after sunset.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 99,
    q: "convict. Example usage: The convict was serving a ten-year sentence for robbery.",
    definition:
      "A person who has been found guilty of a crime and sent to prison.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 100,
    q: "Sentinel. Example usage: In Minecraft, a sentinel stood by the village gate, keeping watch for any mobs nearby.",
    definition: "A guard or someone who keeps watch.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 101,
    q: "Barbarous. Example usage: The barbarous raid in Roblox destroyed our peaceful base without warning.",
    definition: "Cruel or savage in behaviour.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 102,
    q: "Obstruct. Example usage: He tried to obstruct the other team’s striker during the football match but got a yellow card instead.",
    definition: "To block or get in the way of something.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 103,
    q: "Vain. Example usage: She made a vain attempt to fix the broken Lego spaceship without using the instructions.",
    definition: "Unsuccessful or full of pride in one's looks or abilities.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 104,
    q: "Grapple. Example usage: He had to grapple with a tricky problem in his school project before he could go on holiday.",
    definition: "To struggle with something or someone.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 105,
    q: "Endeavour. Example usage: It was a huge endeavour to build a working rollercoaster in Roblox before the school holidays ended.",
    definition: "A serious attempt or effort to do something.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 106,
    q: "Intriguing. Example usage: The new Lego set looked so intriguing that he started building it before even unpacking his holiday suitcase.",
    definition: "Very interesting or mysterious.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 107,
    q: "Pummel. Example usage: In Minecraft, the golem started to pummel the zombie with heavy punches.",
    definition: "To hit repeatedly and hard.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 108,
    q: "Countenance. Example usage: The fan's countenance was joyful after his team won their match.",
    definition: "A person’s face or facial expression.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 109,
    q: "Acquit. Example usage: after reviewing the game logs, the admin decided to acquit the Roblox player of cheating.",
    definition: "To declare someone not guilty of a wrongdoing.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 110,
    q: "Shrubbery. Example usage: while exploring a Minecraft forest, we cleared some shrubbery to build our holiday cabin.",
    definition: "A group of bushes or small plants.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 111,
    q: "Irreconcilable. Example usage: their ideas for the Lego spaceship were so different that they were irreconcilable and they built two separate models instead.",
    definition: "Impossible to agree or make compatible.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 112,
    q: "Graze. Example usage: he got a small graze on his knee after sliding across the football pitch during the final match of the term.",
    definition: "A slight injury where the skin is scraped.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 113,
    q: "Vestige. Example usage: the broken bricks were the last vestige of the Roblox castle we had built before the update wiped it.",
    definition: "A small remaining part of something that once existed.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 114,
    q: "Quench. Example usage: after coding all morning, she drank lemonade to quench her thirst before heading out to play football.",
    definition: "To satisfy thirst or put out a fire.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 115,
    q: "Enhance. Example usage: he used a special plugin to enhance the lighting in his Minecraft world.",
    definition: "To improve something or make it better.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 116,
    q: "Bellicose. Example usage: the bellicose character in the Roblox game kept starting fights even when no one provoked him.",
    definition: "Aggressive and ready to fight.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 117,
    q: "Adjourn. Example usage: the football match had to adjourn for ten minutes because of heavy rain.",
    definition: "To pause or stop a meeting or activity for a short time.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 118,
    q: "Credulous. Example usage: his credulous little brother believed that the Lego minifigures came alive at night.",
    definition: "Easily believes things, especially without evidence.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
  {
    id: 119,
    q: "Odious. Example usage: cleaning up the odious mess left by the slime mob in Minecraft was the worst part of the whole holiday build challenge.",
    definition: "Extremely unpleasant or disgusting.",
    options: ["yes", "no"],
    category: "unknown",
    a: 0,
  },
];

// template
// {
//   id: 2,
//   q: "[]. Example usage: ",
//   definition: "",
//   options: ["yes", "no"],
// category: "unknown",
//   a: 0,
// },
